from __future__ import annotations
import os
import json
import hashlib
import sys
from glob import glob
from dataclasses import dataclass, asdict, is_dataclass, fields
from typing import (
    List, Optional, Union, Any, Type,
    get_origin, get_args, get_type_hints
)
from datetime import datetime
from dateutil import parser   # pip install python-dateutil
from jinja2 import Template

from .utils import UnionFind, nearest_matches, nearest_descriptors, find_central_idx

resource_template = Template("""
# {{resource.source}}
{% if resource.title is not none %}Title: {{ resource.title }}
{% endif %}{% if resource.date is not none %}Date: {{ resource.date }}
{% endif %}{% if resource.flair is not none %}Flair: {{ resource.flair }}
{% endif %}{% if resource.votes is not none %}Upvotes: {{ resource.votes }}
{% endif %}{% if resource.forward_url is not none %}Forward_url: {{ resource.forward_url }}
{% endif %}{% if resource.source is not none %}Source: {{ resource.source }}
{% endif %}{% if resource.description is not none %}Description: {{ resource.description }}
{% endif %}{% if resource.content is not none %}
Content:
{{resource.content}}
{% endif %}{% if resource.comments is not none %}Comments:
{% for comment in resource.comments recursive %}
 - Author: {{ comment.author }} (Votes: {{comment.votes}})
    {{comment.content}}{% endfor %}
{% endif %}
""")


def get_filepath(dir_path: str, url: str) -> str:
    """
    Compute an MD5 hash of the URL and append '.json'.
    """
    filename = hashlib.md5(url.encode('utf-8')).hexdigest() + '.json'
    return os.path.join(dir_path, filename)


@dataclass
class Comment:
    author:   Optional[str]             = None
    votes:    Optional[int]             = None
    content:  Optional[str]             = None
    comments: Optional[List[Comment]]   = None


@dataclass
class Resource:
    location:       str                             # URL for the resource
    crawl_date:     datetime = datetime.now()       # Date when the page was retrieved
    date:           Optional[datetime]  = None      # Date when the page was created
    title:          Optional[str]       = None
    flair:          Optional[str]       = None
    votes:          Optional[int]       = None
    forward_url:    Optional[str]       = None      # Alternate location for Reddit URLs
    source:         Optional[str]       = None      # Origin of info in the URL (publisher, subreddit, main site name, etc...)
    source_logo:    Optional[str]       = None      # Source icon, thumbnail or logo
    media:          Optional[str]       = None
    description:    Optional[str]       = None    
    image:          Optional[str]       = None      # Large image
    thumbnail:      Optional[str]       = None      # Preview image
    content:        Optional[str]       = None        
    comments:       Optional[List[Comment]] = None
    embedding:      Optional[List[float]]   = None
    

    def __post_init__(self):
        """
        Automatically called after the dataclass’s autogenerated __init__.
        If `date` was passed as a string (or anything that isn’t already a datetime),
        convert it once and store the datetime object on the instance.
        """
        if isinstance(self.date, str):
            # Accept both bytes and str just in case.
            self.date = parser.parse(self.date) if isinstance(self.date, (str, bytes)) else datetime.fromisoformat(str(self.date))
        elif not isinstance(self.date, datetime):            
            self.date = None    

        if self.location == self.forward_url:
            self.forward_url = None
            
    def to_dict(self) -> dict:
        self_dict = asdict(self)

        datetime_fields = [k for k, v in self_dict.items() if isinstance(v, datetime)]        

        for datetime_field in datetime_fields:
            self_dict[datetime_field] = self_dict[datetime_field].isoformat()

        return self_dict
      
    @classmethod      
    def from_dict(cls, data):
        return dict_to_dataclass(cls, data)
        
    def serialize(self, dir_path: str) -> None:
        """
        Write this URL (and nested comments) to:
          {dir_path}/{md5(source)}.json
        """

        self_dict = self.to_dict()
        
        os.makedirs(dir_path, exist_ok=True)
        out_path = get_filepath(dir_path, self.location)
            
        with open(out_path, 'w', encoding='utf-8') as fp:
            json.dump(self_dict, fp, ensure_ascii=False, indent=2)

    @classmethod
    def deserialize(cls, dir_path: str, source: str) -> 'Resource':
        """
        Read JSON from:
          {dir_path}/{md5(source)}.json
        and reconstruct a URL instance (with Comment objects).
        """
        in_path = get_filepath(dir_path, source)

        return cls.load(in_path)

    @classmethod
    def load(cls, in_path: str) -> 'Resource':
        """
        Read JSON from:
          {dir_path}/{md5(source)}.json
        and reconstruct a URL instance (with Comment objects).
        """
        
        with open(in_path, 'r', encoding='utf-8') as fp:
            data = json.load(fp)
            
        return cls.from_dict(data)

    @classmethod
    def load_all_from(cls, path:str):
        all_submissions = []
        for json_file in glob(f"{path}/*.json"):
            assert path + json_file.replace(path,"") == json_file
            url = cls.load(json_file)
            all_submissions.append(url)

        return all_submissions

    @classmethod
    def save_all_to(cls, urls: List[Resource], path:str):
        for url in urls:
            url.serialize(path)

    def to_headline(self) -> Resource:
        return Resource(self.location, self.title)
    
    def __str__(self) -> str:
        return resource_template.render(resource=self)
    

def dict_to_dataclass(target_cls: Type[Any], data: dict) -> Any:
    """
    Recursively instantiate dataclass `target_cls` from plain dict `data`,
    correctly handling Optional[...] and List[...] of nested dataclasses,
    even when they were forward‐referenced.
    """
    # give get_type_hints the right globals so it can resolve "Comment"
    module_globals = sys.modules[target_cls.__module__].__dict__
    type_hints = get_type_hints(target_cls, module_globals, module_globals)

    kwargs = {}
    for f in fields(target_cls):
        name = f.name
        if name not in data:
            continue

        raw = data[name]
        typ = type_hints[name]
        origin = get_origin(typ)

        # unwrap Optional[T]
        if origin is Union:
            args = get_args(typ)
            non_none = [a for a in args if a is not type(None)]
            if len(non_none) == 1:
                typ    = non_none[0]
                origin = get_origin(typ)

        # List[T]
        if origin is list:
            inner = get_args(typ)[0]
            if is_dataclass(inner) and raw is not None:
                kwargs[name] = [dict_to_dataclass(inner, itm) for itm in raw]
            else:
                kwargs[name] = raw

        # nested dataclass
        elif is_dataclass(typ) and raw is not None:
            kwargs[name] = dict_to_dataclass(typ, raw)

        # primitive or None
        else:
            kwargs[name] = raw

    return target_cls(**kwargs)

'''
class URLClusterer:
    def __init__(
        self,
        model,
        embedding_distance_threshold = 0.3,
        min_urls_per_cluster = 2,
        ):
        self.model = model
        self.emb_dist_thr = embedding_distance_threshold
        self.min_news_cluster = min_urls_per_cluster

    def __call__(self, urls: List[Resource]):
        
        #for url in urls:
        #    assert url.date
        
        titles = sorted(set([ url.title for url in urls ]))
        embeddings = self.model.embeddings(titles)
        
        # Find matches
        matches = nearest_matches(embeddings, embeddings, self.emb_dist_thr)
                
        uf = UnionFind(len(titles))

        for match in matches:
            uf.union(match[0], match[1])

        clusters = []

        for union in uf.all_sets():
            cluster = []
            
            for idx in union:
                cluster += [ s for s in urls if s.title == titles[idx] ]
                
            #cluster = sorted(cluster, key = lambda sub : sub.date)
                    
            if len(cluster) < self.min_news_cluster:
                continue

            clusters.append(cluster)    
            
        return clusters    
    

    def find_central(self, urls: List[Resource]):
        
        titles = sorted(set([ url.title for url in urls ]))
        embeddings = self.model.embeddings(titles)

        return titles[find_central_idx(embeddings)]
        
        
    def by_keypoint(self, keypoints: List[str], urls: List[Resource]):

        locations = [ url.location for url in urls ]
        assert len(set(locations)) == len(locations)

        titles = sorted(set([ url.title for url in urls ]))
        
        keypoint_embeddings = self.model.embeddings(keypoints)
        titles_embeddings = self.model.embeddings(titles)
        
        matches = { kp : [] for kp in keypoints }
        for url, url_emb in zip(urls, titles_embeddings):
            idxs, __ = nearest_descriptors(keypoint_embeddings, url_emb)
            keypoint = keypoints[idxs[0]]
            matches[keypoint].append(url)
            
        # Sanity check, each url appears only once per keypoint
        for kp, us in matches.items():
            locations = [ u.location for u in us ]
            if len(locations) != len(set(locations)):
                print("********")
                print(keypoint)
                for l in locations:
                    ts = l.split("/")
                    print("\t", ts[6], ts[4])
                
                assert False
            
        return matches
'''        