FRED_series = [
    ['T10Y2Y', '10-Year Treasury Constant Maturity Minus 2-Year Treasury Constant Maturity'],
    ['MORTGAGE30US', '30-Year Fixed Rate Mortgage Average in the United States'],
    ['FEDFUNDS', 'Federal Funds Effective Rate'],
    ['M2SL', 'M2'],
    ['RRPONTSYD', 'Overnight Reverse Repurchase Agreements: Treasury Securities Sold by the Federal Reserve in the Temporary Open Market Operations'],
    ['CPIAUCSL', 'Consumer Price Index for All Urban Consumers: All Items in U.S. City Average'],
    ['UNRATE', 'Unemployment Rate'],
    ['WALCL', 'Assets: Total Assets: Total Assets (Less Eliminations from Consolidation): Wednesday Level'],
    ['T10Y3M', '10-Year Treasury Constant Maturity Minus 3-Month Treasury Constant Maturity'],
    ['GDP', 'Gross Domestic Product'],
    ['GDPC1', 'Real Gross Domestic Product'],
    ['DGS10', 'Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Quoted on an Investment Basis'],
    ['BAMLH0A0HYM2', 'ICE BofA US High Yield Index Option-Adjusted Spread'],
    ['MSPUS', 'Median Sales Price of Houses Sold for the United States'],
    ['CSUSHPINSA', 'S&P CoreLogic Case-Shiller U.S. National Home Price Index'],
    ['T10YIE', '10-Year Breakeven Inflation Rate'],
    ['FPCPITOTLZGUSA', 'Inflation, consumer prices for the United States'],
    ['M1SL', 'M1'],
    ['DRCCLACBS', 'Delinquency Rate on Credit Card Loans, All Commercial Banks'],
    ['DFII10', 'Market Yield on U.S. Treasury Securities at 10-Year Constant Maturity, Quoted on an Investment Basis, Inflation-Indexed'],
    ['ASPUS', 'Average Sales Price of Houses Sold for the United States'],
    ['CORESTICKM159SFRBATL', 'Sticky Price Consumer Price Index less Food and Energy'],
    ['GFDEGDQ188S', 'Federal Debt: Total Public Debt as Percent of Gross Domestic Product'],
    ['PCE', 'Personal Consumption Expenditures'],
    ['CIVPART', 'Labor Force Participation Rate'],
    ['PSAVERT', 'Personal Saving Rate'],
    ['SP500', 'S&P 500'],
    ['T5YIE', '5-Year Breakeven Inflation Rate'],
    ['AAA', "Moody's Seasoned Aaa Corporate Bond Yield"],
    ['TB3MS', '3-Month Treasury Bill Secondary Market Rate, Discount Basis'],
    ['GFDEBTN', 'Federal Debt: Total Public Debt'],
    ['PAYEMS', 'All Employees, Total Nonfarm'],
    ['SOFR', 'Secured Overnight Financing Rate'],
    ['MEHOINUSA672N', 'Real Median Household Income in the United States'],
    ['CPALTT01USM657N', 'Consumer Price Index: All Items: Total for United States'],
    ['USACPALTT01CTGYM', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for United States'],
    ['CPALTT01USQ657N', 'Consumer Price Index: All Items: Total for United States'],
    ['CPALTT01USM659N', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for United States'],
    ['CPALTT01USA657N', 'Consumer Price Index: All Items: Total for United States'],
    ['USACPIALLAINMEI', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for United States'],
    ['USACPALTT01IXNBM', 'Consumer Price Index: All Items: Total for United States'],
    ['BAMLH0A0HYM2EY', 'ICE BofA US High Yield Index Effective Yield'],
    ['CPILFESL', 'Consumer Price Index for All Urban Consumers: All Items Less Food and Energy in U.S. City Average'],
    ['M2V', 'Velocity of M2 Money Stock'],
    ['ICSA', 'Initial Claims'],
    ['DGS1', 'Market Yield on U.S. Treasury Securities at 1-Year Constant Maturity, Quoted on an Investment Basis'],
    ['T5YIFR', '5-Year, 5-Year Forward Inflation Expectation Rate'],
    ['FYFSD', 'Federal Surplus or Deficit [-]'],
    ['LES1252881600Q', 'Employed full time: Median usual weekly real earnings: Wage and salary workers: 16 years and over'],
    ['REAINTRATREARAT10Y', '10-Year Real Interest Rate'],
    ['SAHMREALTIME', 'Real-time Sahm Rule Recession Indicator'],
    ['DGS2', 'Market Yield on U.S. Treasury Securities at 2-Year Constant Maturity, Quoted on an Investment Basis'],
    ['CUSR0000SETA02', 'Consumer Price Index for All Urban Consumers: Used Cars and Trucks in U.S. City Average'],
    ['NFCI', 'Chicago Fed National Financial Conditions Index'],
    ['CCLACBW027SBOG', 'Consumer Loans: Credit Cards and Other Revolving Plans, All Commercial Banks'],
    ['UMCSENT', 'University of Michigan: Consumer Sentiment'],
    ['WTREGEN', 'Liabilities and Capital: Liabilities: Deposits with F.R. Banks, Other Than Reserve Balances: U.S. Treasury, General Account: Week Average'],
    ['PCEPI', 'Personal Consumption Expenditures: Chain-type Price Index'],
    ['DFEDTARU', 'Federal Funds Target Range - Upper Limit'],
    ['BAMLC0A4CBBB', 'ICE BofA BBB US Corporate Index Option-Adjusted Spread'],
    ['INDPRO', 'Industrial Production: Total Index'],
    ['DGS5', 'Market Yield on U.S. Treasury Securities at 5-Year Constant Maturity, Quoted on an Investment Basis'],
    ['RIFLGFCY05NA', 'Market Yield on U.S. Treasury Securities at 5-Year Constant Maturity, Quoted on an Investment Basis'],
    ['HOUST', 'New Privately-Owned Housing Units Started: Total Units'],
    ['DBAA', "Moody's Seasoned Baa Corporate Bond Yield"],
    ['DPSACBW027SBOG', 'Deposits, All Commercial Banks'],
    ['DCOILWTICO', 'Crude Oil Prices: West Texas Intermediate (WTI) - Cushing, Oklahoma'],
    ['ACTLISCOUUS', 'Housing Inventory: Active Listing Count in the United States'],
    ['CES0500000003', 'Average Hourly Earnings of All Employees, Total Private'],
    ['A939RX0Q048SBEA', 'Real gross domestic product per capita'],
    ['PPIACO', 'Producer Price Index by Commodity: All Commodities'],
    ['BOGMBASE', 'Monetary Base: Total'],
    ['PCEC96', 'Real Personal Consumption Expenditures'],
    ['BAMLC0A0CM', 'ICE BofA US Corporate Index Option-Adjusted Spread'],
    ['JTSJOL', 'Job Openings: Total Nonfarm'],
    ['BAMLC0A4CBBBEY', 'ICE BofA BBB US Corporate Index Effective Yield'],
    ['PCEPILFE', 'Personal Consumption Expenditures Excluding Food and Energy (Chain-Type Price Index)'],
    ['TOTALSA', 'Total Vehicle Sales'],
    ['M2REAL', 'Real M2 Money Stock'],
    ['A091RC1Q027SBEA', 'Federal government current expenditures: Interest payments'],
    ['DRSFRMACBS', 'Delinquency Rate on Single-Family Residential Mortgages, Booked in Domestic Offices, All Commercial Banks'],
    ['EFFR', 'Effective Federal Funds Rate'],
    ['DGS30', 'Market Yield on U.S. Treasury Securities at 30-Year Constant Maturity, Quoted on an Investment Basis'],
    ['WRESBAL', 'Liabilities and Capital: Other Factors Draining Reserve Balances: Reserve Balances with Federal Reserve Banks: Week Average'],
    ['DGS20', 'Market Yield on U.S. Treasury Securities at 20-Year Constant Maturity, Quoted on an Investment Basis'],
    ['H41RESPPALDKNWW', 'Assets: Liquidity and Credit Facilities: Loans: Bank Term Funding Program, Net: Wednesday Level'],
    ['MSACSR', 'Monthly Supply of New Houses in the United States'],
    ['CUUR0000SEHA', 'Consumer Price Index for All Urban Consumers: Rent of Primary Residence in U.S. City Average'],
    ['EXHOSLUSM495S', 'Existing Home Sales'],
    ['APU0000708111', 'Average Price: Eggs, Grade A, Large (Cost per Dozen) in U.S. City Average'],
    ['GDPDEF', 'Gross Domestic Product: Implicit Price Deflator'],
    ['WPU0911', 'Producer Price Index by Commodity: Pulp, Paper, and Allied Products: Wood Pulp'],
    ['DTWEXBGS', 'Nominal Broad U.S. Dollar Index'],
    ['MMMFFAQ027S', 'Money Market Funds; Total Financial Assets, Level'],
    ['TDSP', 'Household Debt Service Payments as a Percent of Disposable Personal Income'],
    ['MORTGAGE15US', '15-Year Fixed Rate Mortgage Average in the United States'],
    ['IORB', 'Interest Rate on Reserve Balances (IORB Rate)'],
    ['SOFR30DAYAVG', '30-Day Average SOFR'],
    ['DSPIC96', 'Real Disposable Personal Income'],
    ['FEDTARMD', 'FOMC Summary of Economic Projections for the Fed Funds Rate, Median'],
    ['USSTHPI', 'All-Transactions House Price Index for the United States'],
    ['FYFSGDA188S', 'Federal Surplus or Deficit [-] as Percent of Gross Domestic Product'],
    ['PRIME', 'Bank Prime Loan Rate Changes: Historical Dates of Changes and Rates'],
    ['VIXCLS', 'CBOE Volatility Index: VIX'],
    ['BAA10Y', "Moody's Seasoned Baa Corporate Bond Yield Relative to Yield on 10-Year Treasury Constant Maturity"],
    ['MEPAINUSA672N', 'Real Median Personal Income in the United States'],
    ['DPRIME', 'Bank Prime Loan Rate'],
    ['MPRIME', 'Bank Prime Loan Rate'],
    ['CCSA', 'Continued Claims (Insured Unemployment)'],
    ['GDPPOT', 'Real Potential Gross Domestic Product'],
    ['PCU325211325211', 'Producer Price Index by Industry: Plastics Material and Resin Manufacturing'],
    ['FIXHAI', 'Housing Affordability Index (Fixed)'],
    ['BUSLOANS', 'Commercial and Industrial Loans, All Commercial Banks'],
    ['DGS3MO', 'Market Yield on U.S. Treasury Securities at 3-Month Constant Maturity, Quoted on an Investment Basis'],
    ['CURRCIR', 'Currency in Circulation'],
    ['TOTRESNS', 'Reserves of Depository Institutions: Total'],
    ['DJIA', 'Dow Jones Industrial Average'],
    ['DEXUSEU', 'U.S. Dollars to Euro Spot Exchange Rate'],
    ['STLFSI4', 'St. Louis Fed Financial Stress Index'],
    ['MEDCPIM158SFRBCLE', 'Median Consumer Price Index'],
    ['OPHNFB', 'Nonfarm Business Sector: Labor Productivity (Output per Hour) for All Workers'],
    ['T10YFF', '10-Year Treasury Constant Maturity Minus Federal Funds Rate'],
    ['RECPROUSM156N', 'Smoothed U.S. Recession Probabilities'],
    ['TOTBKCR', 'Bank Credit, All Commercial Banks'],
    ['DRCLACBS', 'Delinquency Rate on Consumer Loans, All Commercial Banks'],
    ['DRTSCILM', 'Net Percentage of Domestic Banks Tightening Standards for Commercial and Industrial Loans to Large and Middle-Market Firms'],
    ['TOTLL', 'Loans and Leases in Bank Credit, All Commercial Banks'],
    ['LLBACBQ158SBOG', 'Loans and Leases in Bank Credit, All Commercial Banks'],
    ['DCOILBRENTEU', 'Crude Oil Prices: Brent - Europe'],
    ['PMSAVE', 'Personal Saving'],
    ['BAMLH0A3HYC', 'ICE BofA CCC & Lower US High Yield Index Option-Adjusted Spread'],
    ['RSXFS', 'Advance Retail Sales: Retail Trade'],
    ['DGS1MO', 'Market Yield on U.S. Treasury Securities at 1-Month Constant Maturity, Quoted on an Investment Basis'],
    ['RHORUSQ156N', 'Homeownership Rate in the United States'],
    ['LNS14000006', 'Unemployment Rate - Black or African American'],
    ['BAMLH0A3HYCEY', 'ICE BofA CCC & Lower US High Yield Index Effective Yield'],
    ['WPU101707', 'Producer Price Index by Commodity: Metals and Metal Products: Cold Rolled Steel Sheet and Strip'],
    ['RRPONTSYAWARD', 'Overnight Reverse Repurchase Agreements Award Rate: Treasury Securities Sold by the Federal Reserve in the Temporary Open Market Operations'],
    ['MEHOINUSA646N', 'Median Household Income in the United States'],
    ['MABMM301USM189S', 'Monetary Aggregates and Their Components: Broad Money and Components: M3 for United States'],
    ['UNEMPLOY', 'Unemployment Level'],
    ['PCUOMFGOMFG', 'Producer Price Index by Industry: Total Manufacturing Industries'],
    ['PERMIT', 'New Privately-Owned Housing Units Authorized in Permit-Issuing Places: Total Units'],
    ['DRALACBN', 'Delinquency Rate on All Loans, All Commercial Banks'],
    ['CUUR0000SETA01', 'Consumer Price Index for All Urban Consumers: New Vehicles in U.S. City Average'],
    ['TREAST', 'Assets: Securities Held Outright: U.S. Treasury Securities: All: Wednesday Level'],
    ['BAMLH0A1HYBB', 'ICE BofA BB US High Yield Index Option-Adjusted Spread'],
    ['HSN1F', 'New One Family Houses Sold: United States'],
    ['GDPNOW', 'GDPNow'],
    ['USREC', 'NBER based Recession Indicators for the United States from the Period following the Peak through the Trough'],
    ['LNS11300060', 'Labor Force Participation Rate - 25-54 Yrs.'],
    ['COMREPUSQ159N', 'Commercial Real Estate Prices for United States'],
    ['MANEMP', 'All Employees, Manufacturing'],
    ['CASTHPI', 'All-Transactions House Price Index for California'],
    ['DRCRELEXFACBS', 'Delinquency Rate on Commercial Real Estate Loans (Excluding Farmland), Booked in Domestic Offices, All Commercial Banks'],
    ['CPIUFDSL', 'Consumer Price Index for All Urban Consumers: Food in U.S. City Average'],
    ['CP', 'Corporate Profits After Tax (without IVA and CCAdj)'],
    ['DFII5', 'Market Yield on U.S. Treasury Securities at 5-Year Constant Maturity, Quoted on an Investment Basis, Inflation-Indexed'],
    ['INTDSRUSM193N', 'Interest Rates, Discount Rate for United States'],
    ['DEXJPUS', 'Japanese Yen to U.S. Dollar Spot Exchange Rate'],
    ['CLF16OV', 'Civilian Labor Force Level'],
    ['DGS3', 'Market Yield on U.S. Treasury Securities at 3-Year Constant Maturity, Quoted on an Investment Basis'],
    ['QCAR628BIS', 'Real Residential Property Prices for Canada'],
    ['DPCCRV1Q225SBEA', 'Personal Consumption Expenditures (PCE) Excluding Food and Energy (Chain-Type Price Index)'],
    ['GASREGW', 'US Regular All Formulations Gas Price'],
    ['MICH', 'University of Michigan: Inflation Expectation'],
    ['POPTHM', 'Population'],
    ['CE16OV', 'Employment Level'],
    ['W006RC1Q027SBEA', 'Federal government current tax receipts'],
    ['NA000327Q', 'Federal government current tax receipts'],
    ['CUUR0000SA0R', 'Consumer Price Index for All Urban Consumers: Purchasing Power of the Consumer Dollar in U.S. City Average'],
    ['NASDAQCOM', 'NASDAQ Composite Index'],
    ['BAMLH0A1HYBBEY', 'ICE BofA BB US High Yield Index Effective Yield'],
    ['NROU', 'Noncyclical Rate of Unemployment'],
    ['HOSINVUSM495N', 'Existing Home Sales: Housing Inventory'],
    ['JHDUSRGDPBR', 'Dates of U.S. recessions as inferred by GDP-based recession indicator'],
    ['AWHAETP', 'Average Weekly Hours of All Employees, Total Private'],
    ['IRLTLT01USM156N', 'Interest Rates: Long-Term Government Bond Yields: 10-Year: Main (Including Benchmark) for United States'],
    ['CUSR0000SAF11', 'Consumer Price Index for All Urban Consumers: Food at Home in U.S. City Average'],
    ['WSHOMCB', 'Assets: Securities Held Outright: Mortgage-Backed Securities: Wednesday Level'],
    ['DSPI', 'Disposable Personal Income'],
    ['QJPN628BIS', 'Residential Property Prices for Japan'],
    ['HDTGPDUSQ163N', 'Household Debt to GDP for United States'],
    ['FGEXPND', 'Federal Government: Current Expenditures'],
    ['TCU', 'Capacity Utilization: Total Index'],
    ['DGORDER', "Manufacturers' New Orders: Durable Goods"],
    ['CREACBM027NBOG', 'Real Estate Loans: Commercial Real Estate Loans, All Commercial Banks'],
    ['IHLIDXUSTPSOFTDEVE', 'Software Development Job Postings on Indeed in the United States'],
    ['TERMCBCCALLNS', 'Commercial Bank Interest Rate on Credit Card Plans, All Accounts'],
    ['IUDSOIA', 'Daily Sterling Overnight Index Average (SONIA) Rate'],
    ['USALOLITONOSTSAM', 'Composite Leading Indicators: Composite Leading Indicator (CLI) Normalized for United States'],
    ['SPCS20RSA', 'S&P CoreLogic Case-Shiller 20-City Composite Home Price Index'],
    ['APU0000703112', 'Average Price: Ground Beef, 100% Beef (Cost per Pound/453.6 Grams) in U.S. City Average'],
    ['M1V', 'Velocity of M1 Money Stock'],
    ['ECIWAG', 'Employment Cost Index: Wages and Salaries: Private Industry Workers'],
    ['APU0000702111', 'Average Price: Bread, White, Pan (Cost per Pound/453.6 Grams) in U.S. City Average'],
    ['CUSR0000SAH1', 'Consumer Price Index for All Urban Consumers: Shelter in U.S. City Average'],
    ['CUUS0000SAH1', 'Consumer Price Index for All Urban Consumers: Shelter in U.S. City Average'],
    ['DHHNGSP', 'Henry Hub Natural Gas Spot Price'],
    ['DEXCHUS', 'Chinese Yuan Renminbi to U.S. Dollar Spot Exchange Rate'],
    ['WRMFNS', 'Retail Money Market Funds'],
    ['WPU10170502', 'Producer Price Index by Commodity: Metals and Metal Products: Steel Wire, Stainless Steel'],
    ['MSPNHSUS', 'Median Sales Price for New Houses Sold in the United States'],
    ['BOGZ1FL192090005Q', 'Households; Net Worth, Level'],
    ['BAMLHE00EHYIEY', 'ICE BofA Euro High Yield Index Effective Yield'],
    ['WEI', 'Weekly Economic Index (Lewis-Mertens-Stock)'],
    ['EXPINF10YR', '10-Year Expected Inflation'],
    ['THREEFYTP10', 'Term Premium on a 10 Year Zero Coupon Bond'],
    ['QCNR628BIS', 'Real Residential Property Prices for China'],
    ['GFDGDPA188S', 'Gross Federal Debt as Percent of Gross Domestic Product'],
    ['A261RX1Q020SBEA', 'Real gross domestic income'],
    ['GDI', 'Gross Domestic Income'],
    ['PNGASJPUSDM', 'Global price of LNG, Asia'],
    ['RRVRUSQ156N', 'Rental Vacancy Rate in the United States'],
    ['PURANUSDM', 'Global price of Uranium'],
    ['NGDPSAXDCUSQ', 'Nominal Gross Domestic Product for United States'],
    ['ACTLISCOUFL', 'Housing Inventory: Active Listing Count in Florida'],
    ['A229RX0', 'Real Disposable Personal Income: Per Capita'],
    ['RESPPANWW', 'Assets: Total Assets: Total Assets: Wednesday Level'],
    ['WFRBST01134', 'Share of Total Net Worth Held by the Top 1% (99th to 100th Wealth Percentiles)'],
    ['BAMLH0A2HYBEY', 'ICE BofA Single-B US High Yield Index Effective Yield'],
    ['JTSLDL', 'Layoffs and Discharges: Total Nonfarm'],
    ['JTULDL', 'Layoffs and Discharges: Total Nonfarm'],
    ['EMRATIO', 'Employment-Population Ratio'],
    ['U6RATE', 'Total Unemployed, Plus All Persons Marginally Attached to the Labor Force, Plus Total Employed Part Time for Economic Reasons, as a Percent of the Civilian Labor Force Plus All Persons Marginally Attached to the Labor Force (U-6)'],
    ['AHETPI', 'Average Hourly Earnings of Production and Nonsupervisory Employees, Total Private'],
    ['TEDRATE', 'TED Spread (DISCONTINUED)'],
    ['APU000072610', 'Average Price: Electricity per Kilowatt-Hour in U.S. City Average'],
    ['LNS11300002', 'Labor Force Participation Rate - Women'],
    ['BAMLHE00EHYIOAS', 'ICE BofA Euro High Yield Index Option-Adjusted Spread'],
    ['TTLCONS', 'Total Construction Spending: Total Construction in the United States'],
    ['USCONS', 'All Employees, Construction'],
    ['AAA10Y', "Moody's Seasoned Aaa Corporate Bond Yield Relative to Yield on 10-Year Treasury Constant Maturity"],
    ['SOFR90DAYAVG', '90-Day Average SOFR'],
    ['JPNRGDPEXP', 'Real Gross Domestic Product for Japan'],
    ['BAMLC0A1CAAAEY', 'ICE BofA AAA US Corporate Index Effective Yield'],
    ['USSLIND', 'Leading Index for the United States'],
    ['PCOPPUSDM', 'Global price of Copper'],
    ['WTISPLC', 'Spot Crude Oil Price: West Texas Intermediate (WTI)'],
    ['HOUST1F', 'New Privately-Owned Housing Units Started: Single-Family Units'],
    ['HOSMEDUSM052N', 'Median Sales Price of Existing Homes'],
    ['RESPPLLOPNWW', 'Liabilities and Capital: Liabilities: Earnings Remittances Due to the U.S. Treasury: Wednesday Level'],
    ['PI', 'Personal Income'],
    ['APU0000FF1101', 'Average Price: Chicken Breast, Boneless (Cost per Pound/453.6 Grams) in U.S. City Average'],
    ['ALTSALES', 'Light Weight Vehicle Sales: Autos and Light Trucks'],
    ['JTSQUR', 'Quits: Total Nonfarm'],
    ['IHLIDXUS', 'Job Postings on Indeed in the United States'],
    ['OBMMIJUMBO30YF', '30-Year Fixed Rate Jumbo Mortgage Index'],
    ['WRBWFRBL', 'Liabilities and Capital: Other Factors Draining Reserve Balances: Reserve Balances with Federal Reserve Banks: Wednesday Level'],
    ['PCU32733273', 'Producer Price Index by Industry: Cement and Concrete Product Manufacturing'],
    ['REAINTRATREARAT1YE', '1-Year Real Interest Rate'],
    ['IC4WSA', '4-Week Moving Average of Initial Claims'],
    ['FLSTHPI', 'All-Transactions House Price Index for Florida'],
    ['WPU061', 'Producer Price Index by Commodity: Chemicals and Allied Products: Industrial Chemicals'],
    ['POLVOILUSDM', 'Global price of Olive Oil'],
    ['HTRUCKSSAAR', 'Motor Vehicle Retail Sales: Heavy Weight Trucks'],
    ['GPDI', 'Gross Private Domestic Investment'],
    ['USGOVT', 'All Employees, Government'],
    ['EXPINF1YR', '1-Year Expected Inflation'],
    ['QUSR628BIS', 'Real Residential Property Prices for United States'],
    ['DGS6MO', 'Market Yield on U.S. Treasury Securities at 6-Month Constant Maturity, Quoted on an Investment Basis'],
    ['PALLFNFINDEXQ', 'Global Price Index of All Commodities'],
    ['AUINSA', 'Domestic Auto Inventories'],
    ['PWHEAMTUSDM', 'Global price of Wheat'],
    ['BAMLC0A0CMEY', 'ICE BofA US Corporate Index Effective Yield'],
    ['CAUR', 'Unemployment Rate in California'],
    ['SFXRSA', 'S&P CoreLogic Case-Shiller CA-San Francisco Home Price Index'],
    ['ETOTALUSQ176N', 'Housing Inventory Estimate: Total Housing Units in the United States'],
    ['SIPOVGINIUSA', 'GINI Index for the United States'],
    ['SAHMCURRENT', 'Sahm Rule Recession Indicator'],
    ['FYONGDA188S', 'Federal Net Outlays as Percent of Gross Domestic Product'],
    ['WPU101', 'Producer Price Index by Commodity: Metals and Metal Products: Iron and Steel'],
    ['PPIFIS', 'Producer Price Index by Commodity: Final Demand'],
    ['GPDIC1', 'Real Gross Private Domestic Investment'],
    ['NB000335Q', 'Real Gross Private Domestic Investment'],
    ['CES4348400001', 'All Employees, Truck Transportation'],
    ['CPIENGSL', 'Consumer Price Index for All Urban Consumers: Energy in U.S. City Average'],
    ['TLAACBW027SBOG', 'Total Assets, All Commercial Banks'],
    ['TEMPHELPS', 'All Employees, Temporary Help Services'],
    ['PCETRIM12M159SFRBDAL', 'Trimmed Mean PCE Inflation Rate'],
    ['FYOIGDA188S', 'Federal Outlays: Interest as Percent of Gross Domestic Product'],
    ['PCEDG', 'Personal Consumption Expenditures: Durable Goods'],
    ['GNP', 'Gross National Product'],
    ['BAMLC0A3CA', 'ICE BofA Single-A US Corporate Index Option-Adjusted Spread'],
    ['CPIAPPSL', 'Consumer Price Index for All Urban Consumers: Apparel in U.S. City Average'],
    ['PNRGINDEXM', 'Global price of Energy index'],
    ['PCU325325', 'Producer Price Index by Industry: Chemical Manufacturing'],
    ['WPSFD4131', 'Producer Price Index by Commodity: Final Demand: Finished Goods Less Foods and Energy'],
    ['WDTGAL', 'Liabilities and Capital: Liabilities: Deposits with F.R. Banks, Other Than Reserve Balances: U.S. Treasury, General Account: Wednesday Level'],
    ['DRBLACBS', 'Delinquency Rate on Business Loans, All Commercial Banks'],
    ['UNDCONTSA', 'New Privately-Owned Housing Units Under Construction: Total Units'],
    ['MEDDAYONMARUS', 'Housing Inventory: Median Days on Market in the United States'],
    ['DGS7', 'Market Yield on U.S. Treasury Securities at 7-Year Constant Maturity, Quoted on an Investment Basis'],
    ['DTB1YR', '1-Year Treasury Bill Secondary Market Rate, Discount Basis'],
    ['TB1YR', '1-Year Treasury Bill Secondary Market Rate, Discount Basis'],
    ['ECBASSETSW', 'Central Bank Assets for Euro Area (11-19 Countries)'],
    ['PNGASEUUSDM', 'Global price of Natural gas, EU'],
    ['USPRIV', 'All Employees, Total Private'],
    ['CLVMNACSCAB1GQDE', 'Real Gross Domestic Product for Germany'],
    ['DPCREDIT', 'Discount Window Primary Credit Rate'],
    ['NPTLTL', 'Nonperforming Total Loans (past due 90+ days plus nonaccrual) to Total Loans (DISCONTINUED)'],
    ['MDSP', 'Mortgage Debt Service Payments as a Percent of Disposable Personal Income'],
    ['PCU4841214841212', 'Producer Price Index by Industry: General Freight Trucking, Long-Distance Truckload: General Freight Trucking, Long-Distance, Truckload'],
    ['AMTMNO', "Manufacturers' New Orders: Total Manufacturing"],
    ['CUSR0000SEFV', 'Consumer Price Index for All Urban Consumers: Food Away from Home in U.S. City Average'],
    ['WPUSI012011', 'Producer Price Index by Commodity: Special Indexes: Construction Materials'],
    ['LFWA64TTUSM647S', 'Infra-Annual Labor Statistics: Working-Age Population Total: From 15 to 64 Years for United States'],
    ['ECOMPCTSA', 'E-Commerce Retail Sales as a Percent of Total Sales'],
    ['SNDR', 'National Rate: Savings'],
    ['NEWORDER', "Manufacturers' New Orders: Nondefense Capital Goods Excluding Aircraft"],
    ['WPU091405', 'Producer Price Index by Commodity: Pulp, Paper, and Allied Products: Corrugated Paperboard in Sheets and Rolls, Lined and Unlined'],
    ['M2', 'M2 (DISCONTINUED)'],
    ['LXXRSA', 'S&P CoreLogic Case-Shiller CA-Los Angeles Home Price Index'],
    ['DEXCAUS', 'Canadian Dollars to U.S. Dollar Spot Exchange Rate'],
    ['CBBTCUSD', 'Coinbase Bitcoin'],
    ['WPU10', 'Producer Price Index by Commodity: Metals and Metal Products'],
    ['DEXUSUK', 'U.S. Dollars to U.K. Pound Sterling Spot Exchange Rate'],
    ['EXUSUK', 'U.S. Dollars to U.K. Pound Sterling Spot Exchange Rate'],
    ['DRCCLOBS', 'Delinquency Rate on Credit Card Loans, Banks Not Among the 100 Largest in Size by Assets'],
    ['BAMLH0A2HYB', 'ICE BofA Single-B US High Yield Index Option-Adjusted Spread'],
    ['PCU484484', 'Producer Price Index by Industry: Truck Transportation'],
    ['FYFRGDA188S', 'Federal Receipts as Percent of Gross Domestic Product'],
    ['OBMMIVA30YF', '30-Year Fixed Rate Veterans Affairs Mortgage Index'],
    ['MYAGM2USM052S', 'M2 for United States'],
    ['NYSTHPI', 'All-Transactions House Price Index for New York'],
    ['CUSR0000SASLE', 'Consumer Price Index for All Urban Consumers: Services Less Energy Services in U.S. City Average'],
    ['FDHBFRBN', 'Federal Debt Held by Federal Reserve Banks'],
    ['TLMFGCONS', 'Total Construction Spending: Manufacturing in the United States'],
    ['WLRRAL', 'Liabilities and Capital: Liabilities: Reverse Repurchase Agreements: Wednesday Level'],
    ['BAMLHYH0A0HYM2TRIV', 'ICE BofA US High Yield Index Total Return Index Value'],
    ['TOTALSL', 'Total Consumer Credit Owned and Securitized'],
    ['APU0000709112', 'Average Price: Milk, Fresh, Whole, Fortified (Cost per Gallon/3.8 Liters) in U.S. City Average'],
    ['DFEDTARL', 'Federal Funds Target Range - Lower Limit'],
    ['WPU081', 'Producer Price Index by Commodity: Lumber and Wood Products: Lumber'],
    ['GBRCPIALLMINMEI', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for United Kingdom'],
    ['CPALTT01GBQ657N', 'Consumer Price Index: All Items: Total for United Kingdom'],
    ['CPALTT01GBQ659N', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for United Kingdom'],
    ['CPALTT01GBM657N', 'Consumer Price Index: All Items: Total for United Kingdom'],
    ['GBRCPIALLAINMEI', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for United Kingdom'],
    ['GBRCPALTT01IXNBM', 'Consumer Price Index: All Items: Total for United Kingdom'],
    ['PCU33443344', 'Producer Price Index by Industry: Semiconductor and Other Electronic Component Manufacturing'],
    ['RRSFS', 'Advance Real Retail and Food Services Sales'],
    ['MKTGDPCNA646NWDB', 'Gross Domestic Product for China'],
    ['SOFRINDEX', 'SOFR Index'],
    ['RETAILIRSA', 'Retailers: Inventories to Sales Ratio'],
    ['QAUR628BIS', 'Real Residential Property Prices for Australia'],
    ['DDDM01USA156NWDB', 'Stock Market Capitalization to GDP for United States'],
    ['PALUMUSDM', 'Global price of Aluminum'],
    ['PALUMUSDA', 'Global price of Aluminum'],
    ['CDSP', 'Consumer Debt Service Payments as a Percent of Disposable Personal Income'],
    ['PCU484121484121', 'Producer Price Index by Industry: General Freight Trucking, Long-Distance Truckload'],
    ['CUSR0000SETB01', 'Consumer Price Index for All Urban Consumers: Gasoline (All Types) in U.S. City Average'],
    ['LNS11300001', 'Labor Force Participation Rate - Men'],
    ['HOSSUPUSM673N', 'Existing Home Sales: Months Supply'],
    ['BAMLC0A2CAAEY', 'ICE BofA AA US Corporate Index Effective Yield'],
    ['CPIMEDSL', 'Consumer Price Index for All Urban Consumers: Medical Care in U.S. City Average'],
    ['BOPGSTB', 'Trade Balance: Goods and Services, Balance of Payments Basis'],
    ['STICKCPIM157SFRBATL', 'Sticky Price Consumer Price Index'],
    ['IPMAN', 'Industrial Production: Manufacturing (NAICS)'],
    ['TERMCBAUTO48NS', 'Finance Rate on Consumer Installment Loans at Commercial Banks, New Autos 48 Month Loan'],
    ['PCU335311335311', 'Producer Price Index by Industry: Electric Power and Specialty Transformer Manufacturing'],
    ['POILBREUSDM', 'Global price of Brent Crude'],
    ['DTB4WK', '4-Week Treasury Bill Secondary Market Rate, Discount Basis'],
    ['RPONTSYD', 'Overnight Repurchase Agreements: Treasury Securities Purchased by the Federal Reserve in the Temporary Open Market Operations'],
    ['PCU325510325510', 'Producer Price Index by Industry: Paint and Coating Manufacturing'],
    ['DFII30', 'Market Yield on U.S. Treasury Securities at 30-Year Constant Maturity, Quoted on an Investment Basis, Inflation-Indexed'],
    ['HQMCB10YR', '10-Year High Quality Market (HQM) Corporate Bond Spot Rate'],
    ['BOGZ1FL193020005Q', 'Households; Checkable Deposits and Currency; Asset, Level'],
    ['CHNCPIALLMINMEI', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for China'],
    ['CPALTT01CNM657N', 'Consumer Price Index: All Items: Total for China'],
    ['CHNCPIALLQINMEI', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for China'],
    ['CHNCPALTT01IXNBM', 'Consumer Price Index: All Items: Total for China'],
    ['CHNCPIALLAINMEI', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for China'],
    ['CPALTT01CNQ657N', 'Consumer Price Index: All Items: Total for China'],
    ['CPALTT01CNA657N', 'Consumer Price Index: All Items: Total for China'],
    ['CPALTT01CNA659N', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for China'],
    ['CHNCPALTT01IXNBQ', 'Consumer Price Index: All Items: Total for China'],
    ['PCU333132333132', 'Producer Price Index by Industry: Oil and Gas Field Machinery and Equipment Manufacturing'],
    ['STLENI', 'St. Louis Fed Economic News Index: Real GDP Nowcast'],
    ['PNICKUSDM', 'Global price of Nickel'],
    ['CUSR0000SAM2', 'Consumer Price Index for All Urban Consumers: Medical Care Services in U.S. City Average'],
    ['FDHBFIN', 'Federal Debt Held by Foreign and International Investors'],
    ['SEXRNSA', 'S&P CoreLogic Case-Shiller WA-Seattle Home Price Index'],
    ['ISRATIO', 'Total Business: Inventories to Sales Ratio'],
    ['PCU311311', 'Producer Price Index by Industry: Food Manufacturing'],
    ['RSAFS', 'Advance Retail Sales: Retail Trade and Food Services'],
    ['WPU1017', 'Producer Price Index by Commodity: Metals and Metal Products: Steel Mill Products'],
    ['M1REAL', 'Real M1 Money Stock'],
    ['USEPUINDXD', 'Economic Policy Uncertainty Index for United States'],
    ['CUSR0000SEHF01', 'Consumer Price Index for All Urban Consumers: Electricity in U.S. City Average'],
    ['BOGZ1FL075035503Q', 'Interest Rates and Price Indexes; Commercial Real Estate Price Index, Level'],
    ['BAMLC0A3CAEY', 'ICE BofA Single-A US Corporate Index Effective Yield'],
    ['ANFCI', 'Chicago Fed Adjusted National Financial Conditions Index'],
    ['WLCFLPCL', 'Assets: Liquidity and Credit Facilities: Loans: Primary Credit: Wednesday Level'],
    ['A792RC0Q052SBEA', 'Personal income per capita'],
    ['NGDPRSAXDCCAQ', 'Real Gross Domestic Product for Canada'],
    ['TRFVOLUSM227NFWA', 'Vehicle Miles Traveled'],
    ['PCU325412325412', 'Producer Price Index by Industry: Pharmaceutical Preparation Manufacturing'],
    ['JHGDPBRINDX', 'GDP-Based Recession Indicator Index'],
    ['PCU44414441', 'Producer Price Index by Industry: Building Material and Supplies Dealers'],
    ['DPCERE1Q156NBEA', 'Shares of gross domestic product: Personal consumption expenditures'],
    ['NIKKEI225', 'Nikkei Stock Average, Nikkei 225'],
    ['PCU483111483111', 'Producer Price Index by Industry: Deep Sea Freight Transportation'],
    ['PPIIDC', 'Producer Price Index by Commodity: Industrial Commodities'],
    ['PCES', 'Personal Consumption Expenditures: Services'],
    ['PCESV', 'Personal Consumption Expenditures: Services'],
    ['BCNSDODNS', 'Nonfinancial Corporate Business; Debt Securities and Loans; Liability, Level'],
    ['PPIDCS', 'Producer Price Index by Commodity: Final Demand: Final Demand Construction'],
    ['MEPAINUSA646N', 'Median Personal Income in the United States'],
    ['MORTGAGE5US', '5/1-Year Adjustable Rate Mortgage Average in the United States (DISCONTINUED)'],
    ['JPNCPIALLMINMEI', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for Japan'],
    ['CPALTT01JPQ657N', 'Consumer Price Index: All Items: Total for Japan'],
    ['CPALTT01JPQ659N', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for Japan'],
    ['CPALTT01JPM657N', 'Consumer Price Index: All Items: Total for Japan'],
    ['CPALTT01JPA659N', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for Japan'],
    ['CPALTT01JPA657N', 'Consumer Price Index: All Items: Total for Japan'],
    ['DEXKOUS', 'South Korean Won to U.S. Dollar Spot Exchange Rate'],
    ['OBMMIFHA30YF', '30-Year Fixed Rate FHA Mortgage Index'],
    ['ADPWNUSNERSA', 'Total Nonfarm Private Payroll Employment'],
    ['D2WLTGAL', 'Liabilities and Capital: Liabilities: Deposits: U.S. Treasury General Account: Wednesday Level in Federal Reserve District 2: New York'],
    ['WPU057303', 'Producer Price Index by Commodity: Fuels and Related Products and Power: No. 2 Diesel Fuel'],
    ['WPU101211', 'Producer Price Index by Commodity: Metals and Metal Products: Carbon Steel Scrap'],
    ['CONSUMER', 'Consumer Loans, All Commercial Banks'],
    ['RTFPNAUSA632NRUG', 'Total Factor Productivity at Constant National Prices for United States'],
    ['REVOLSL', 'Revolving Consumer Credit Owned and Securitized'],
    ['DEXMXUS', 'Mexican Pesos to U.S. Dollar Spot Exchange Rate'],
    ['DTB6', '6-Month Treasury Bill Secondary Market Rate, Discount Basis'],
    ['CORCCACBS', 'Charge-Off Rate on Credit Card Loans, All Commercial Banks'],
    ['PCUATRNWRATRNWR', 'Producer Price Index by Industry: Transportation and Warehousing Industries'],
    ['NETEXP', 'Net Exports of Goods and Services'],
    ['LNS12026620', 'Multiple Jobholders as a Percent of Employed'],
    ['ECBDFR', 'ECB Deposit Facility Rate for Euro Area'],
    ['USLAH', 'All Employees, Leisure and Hospitality'],
    ['LIOR3M', '3-month London Interbank Offered Rate (LIBOR)'],
    ['RCCCBBALTOT', 'Large Bank Consumer Credit Card Balances: Total Balances'],
    ['USTRADE', 'All Employees, Retail Trade'],
    ['QBPBSTAS', 'Balance Sheet: Total Assets'],
    ['TLNRESCONS', 'Total Construction Spending: Nonresidential in the United States'],
    ['OBFR', 'Overnight Bank Funding Rate'],
    ['UKNGDP', 'Gross Domestic Product for United Kingdom'],
    ['USPBS', 'All Employees, Professional and Business Services'],
    ['BAMLC0A2CAA', 'ICE BofA AA US Corporate Index Option-Adjusted Spread'],
    ['PCU335313335313', 'Producer Price Index by Industry: Switchgear and Switchboard Apparatus Manufacturing'],
    ['M318501Q027NBEA', 'Federal government budget surplus or deficit (-)'],
    ['JPNNGDP', 'Gross Domestic Product for Japan'],
    ['DAUPSA', 'Domestic Auto Production'],
    ['PCU332911332911', 'Producer Price Index by Industry: Industrial Valve Manufacturing'],
    ['AMVPNO', "Manufacturers' New Orders: Motor Vehicles and Parts"],
    ['PCU331315331315', 'Producer Price Index by Industry: Aluminum Sheet, Plate, and Foil Manufacturing'],
    ['SWPT', 'Assets: Central Bank Liquidity Swaps: Central Bank Liquidity Swaps: Wednesday Level'],
    ['USINFO', 'All Employees, Information'],
    ['PPIFES', 'Producer Price Index by Commodity: Final Demand: Final Demand Less Foods and Energy'],
    ['BUSINV', 'Total Business Inventories'],
    ['LNS12300060', 'Employment-Population Ratio - 25-54 Yrs.'],
    ['WPU012', 'Producer Price Index by Commodity: Farm Products: Grains'],
    ['CUSR0000SEHC', "Consumer Price Index for All Urban Consumers: Owners' Equivalent Rent of Residences in U.S. City Average"],
    ['CES1021100001', 'All Employees, Oil and Gas Extraction'],
    ['W068RCQ027SBEA', 'Government total expenditures'],
    ['RRPONTTLD', 'Overnight Reverse Repurchase Agreements: Total Securities Sold by the Federal Reserve in the Temporary Open Market Operations'],
    ['CPIHOSNS', 'Consumer Price Index for All Urban Consumers: Housing in U.S. City Average'],
    ['T30YIEM', '30-year Breakeven Inflation Rate'],
    ['EXPINF30YR', '30-Year Expected Inflation'],
    ['WPU07110224', 'Producer Price Index by Commodity: Rubber and Plastic Products: Synthetic Rubber, Including Styrene-Butadiene Rubber (SBR) and Ethylene Propylene'],
    ['APU0000FN1101', 'Average Price: All Soft Drinks (Cost per 2 Liters/67.6 Ounces) in U.S. City Average'],
    ['AISRSA', 'Auto Inventory/Sales Ratio'],
    ['USEHS', 'All Employees, Private Education and Health Services'],
    ['OEHRENWBSHNO', "Households; Owners' Equity in Real Estate, Level"],
    ['SDXRSA', 'S&P CoreLogic Case-Shiller CA-San Diego Home Price Index'],
    ['FYGFD', 'Gross Federal Debt'],
    ['A939RC0Q052SBEA', 'Gross domestic product per capita'],
    ['WPU08', 'Producer Price Index by Commodity: Lumber and Wood Products'],
    ['PCU333611333611', 'Producer Price Index by Industry: Turbine and Turbine Generator Set Units Manufacturing'],
    ['SLOAS', 'Student Loans Owned and Securitized'],
    ['HOUST5F', 'New Privately-Owned Housing Units Started: Units in Buildings with 5 Units or More'],
    ['RIFSPPFAAD90NB', '90-Day AA Financial Commercial Paper Interest Rate'],
    ['PCU3272132721', 'Producer Price Index by Industry: Glass and Glass Product Manufacturing'],
    ['QDER628BIS', 'Real Residential Property Prices for Germany'],
    ['USPHCI', 'Coincident Economic Activity Index for the United States'],
    ['CES4300000001', 'All Employees, Transportation and Warehousing'],
    ['GDPC1CTM', 'FOMC Summary of Economic Projections for the Growth Rate of Real Gross Domestic Product, Central Tendency, Midpoint'],
    ['BAMLC0A1CAAA', 'ICE BofA AAA US Corporate Index Option-Adjusted Spread'],
    ['JTSHIL', 'Hires: Total Nonfarm'],
    ['WLODLL', 'Liabilities and Capital: Liabilities: Deposits: Other Deposits Held by Depository Institutions: Wednesday Level'],
    ['DFEDTAR', 'Federal Funds Target Rate (DISCONTINUED)'],
    ['IRLTLT01DEM156N', 'Interest Rates: Long-Term Government Bond Yields: 10-Year: Main (Including Benchmark) for Germany'],
    ['AWHMAN', 'Average Weekly Hours of Production and Nonsupervisory Employees, Manufacturing'],
    ['PCUARETTRARETTR', 'Producer Price Index by Industry: Total Retail Trade Industries'],
    ['STTMINWGOH', 'State Minimum Wage Rate for Ohio'],
    ['USFIRE', 'All Employees, Financial Activities'],
    ['PCU336413336413', 'Producer Price Index by Industry: Other Aircraft Parts and Equipment Manufacturing'],
    ['DDOM01USA644NWDB', 'Number of Listed Companies for United States'],
    ['PCU333120333120', 'Producer Price Index by Industry: Construction Machinery Manufacturing'],
    ['PPIDES', 'Producer Price Index by Commodity: Final Demand: Final Demand Energy'],
    ['PCU331110331110', 'Producer Price Index by Industry: Iron and Steel Mills and Ferroalloy Manufacturing'],
    ['PCU336110336110', 'Producer Price Index by Industry: Automobile, Light Truck and Utility Vehicle Manufacturing'],
    ['USAUCSFRCONDOSMSAMID', 'Zillow Home Value Index (ZHVI) for All Homes Including Single-Family Residences, Condos, and CO-OPs in the United States of America'],
    ['IRLTLT01JPM156N', 'Interest Rates: Long-Term Government Bond Yields: 10-Year: Main (Including Benchmark) for Japan'],
    ['INDCPIALLMINMEI', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for India'],
    ['INDCPALTT01IXNBM', 'Consumer Price Index: All Items: Total for India'],
    ['INDCPIALLAINMEI', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for India'],
    ['INDCPALTT01IXNBQ', 'Consumer Price Index: All Items: Total for India'],
    ['CPALTT01INA659N', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for India'],
    ['PCU221122221122', 'Producer Price Index by Industry: Electric Power Distribution'],
    ['EXPINF2YR', '2-Year Expected Inflation'],
    ['CURRSL', 'Currency Component of M1'],
    ['PCU32221132221102', 'Producer Price Index by Industry: Corrugated and Solid Fiber Box Manufacturing: Corrugated Shipping Containers for Paper and Allied Products'],
    ['LABSHPUSA156NRUG', 'Share of Labour Compensation in GDP at Current National Prices for United States'],
    ['DRCCLT100S', 'Delinquency Rate on Credit Card Loans, Banks Ranked 1st to 100th Largest in Size by Assets'],
    ['DRCCLT100N', 'Delinquency Rate on Credit Card Loans, Banks Ranked 1st to 100th Largest in Size by Assets'],
    ['RPI', 'Real Personal Income'],
    ['STTMINWGMA', 'State Minimum Wage Rate for Massachusetts'],
    ['WPU0571', 'Producer Price Index by Commodity: Fuels and Related Products and Power: Gasoline'],
    ['IOER', 'Interest Rate on Excess Reserves (IOER Rate) (DISCONTINUED)'],
    ['WPSFD4111', 'Producer Price Index by Commodity: Final Demand: Finished Consumer Foods'],
    ['PIORECRUSDM', 'Global price of Iron Ore'],
    ['PCU325120325120', 'Producer Price Index by Industry: Industrial Gas Manufacturing'],
    ['PCU336412336412', 'Producer Price Index by Industry: Aircraft Engine and Engine Parts Manufacturing'],
    ['CNP16OV', 'Population Level'],
    ['IITTRHB', 'U.S Individual Income Tax: Tax Rates for Regular Tax: Highest Bracket'],
    ['PCU324191324191', 'Producer Price Index by Industry: Petroleum Lubricating Oil and Grease Manufacturing'],
    ['PCU325212325212P', 'Producer Price Index by Industry: Synthetic Rubber Manufacturing: Primary Products'],
    ['CUSR0000SAM1', 'Consumer Price Index for All Urban Consumers: Medical Care Commodities in U.S. City Average'],
    ['STTMINWGTX', 'State Minimum Wage Rate for Texas'],
    ['PCU481481', 'Producer Price Index by Industry: Air Transportation'],
    ['EXVZUS', 'Venezuelan Bolivares to U.S. Dollar Spot Exchange Rate'],
    ['PCUAWHLTRAWHLTR', 'Producer Price Index by Industry: Total Wholesale Trade Industries'],
    ['APU0000718311', 'Average Price: Potato Chips (Cost per 16 Ounces) in U.S. City Average'],
    ['COMPUTSA', 'New Privately-Owned Housing Units Completed: Total Units'],
    ['APU0200FN1102', 'Average Price: All Soft Drinks, 12 Pk, 12 Ounce, Cans (Cost per 12 Ounces/354.9 Milliliters) in the Midwest Census Region - Urban'],
    ['DRTSCLCC', 'Net Percentage of Domestic Banks Tightening Standards for Credit Card Loans'],
    ['WPUID61', 'Producer Price Index by Commodity: Intermediate Demand by Commodity Type: Processed Goods for Intermediate Demand'],
    ['CES4348100001', 'All Employees, Air Transportation'],
    ['WFRBLTP1246', 'Net Worth Held by the Top 0.1% (99.9th to 100th Wealth Percentiles)'],
    ['PPIDGS', 'Producer Price Index by Commodity: Final Demand: Final Demand Goods'],
    ['USMINE', 'All Employees, Mining and Logging'],
    ['PCU441110441110', 'Producer Price Index by Industry: New Car Dealers'],
    ['JPNASSETS', 'Bank of Japan: Total Assets for Japan'],
    ['WPU5121', 'Producer Price Index by Commodity: Health Care Services: Inpatient Care'],
    ['CWUR0000SA0', 'Consumer Price Index for All Urban Wage Earners and Clerical Workers: All Items in U.S. City Average'],
    ['TRUCKD11', 'Truck Tonnage Index'],
    ['IRLTLT01GBM156N', 'Interest Rates: Long-Term Government Bond Yields: 10-Year: Main (Including Benchmark) for United Kingdom'],
    ['ATNHPIUS12420Q', 'All-Transactions House Price Index for Austin-Round Rock-Georgetown, TX (MSA)'],
    ['WPU1411', 'Producer Price Index by Commodity: Transportation Equipment: Motor Vehicles'],
    ['ACTLISCOUCA', 'Housing Inventory: Active Listing Count in California'],
    ['PCU622110622110', 'Producer Price Index by Industry: General Medical and Surgical Hospitals'],
    ['WPSFD49116', 'Producer Price Index by Commodity: Final Demand: Final Demand Less Foods, Energy, and Trade Services'],
    ['CES2000000003', 'Average Hourly Earnings of All Employees, Construction'],
    ['TMBACBW027SBOG', 'Treasury and Agency Securities: Mortgage-Backed Securities (MBS), All Commercial Banks'],
    ['USWTRADE', 'All Employees, Wholesale Trade'],
    ['CES3000000003', 'Average Hourly Earnings of All Employees, Manufacturing'],
    ['PPIDSS', 'Producer Price Index by Commodity: Final Demand: Final Demand Services'],
    ['SPDYNCBRTINUSA', 'Crude Birth Rate for the United States'],
    ['M0892AUSM156SNBR', 'Unemployment Rate for United States'],
    ['WPU0221', 'Producer Price Index by Commodity: Processed Foods and Feeds: Meats'],
    ['FYGFDPUN', 'Federal Debt Held by the Public'],
    ['PCU332991332991', 'Producer Price Index by Industry: Ball and Roller Bearing Manufacturing'],
    ['WPU43', 'Producer Price Index by Commodity: Real Estate Services (Partial)'],
    ['PCU445110445110', 'Producer Price Index by Industry: Supermarkets and Other Grocery Stores'],
    ['WPU5831', 'Producer Price Index by Commodity: Retail Trade Services: Apparel, Jewelry, Footwear, and Accessories Retailing'],
    ['CPIEDUSL', 'Consumer Price Index for All Urban Consumers: Education and Communication in U.S. City Average'],
    ['WPU5811', 'Producer Price Index by Commodity: Retail Trade Services: Food and Alcohol Retailing'],
    ['CLVMNACSCAB1GQIT', 'Real Gross Domestic Product for Italy'],
    ['PCU482111482111', 'Producer Price Index by Industry: Line-Haul Railroads'],
    ['BAMLEMCBPIOAS', 'ICE BofA Emerging Markets Corporate Plus Index Option-Adjusted Spread'],
    ['PCU325199325199P', 'Producer Price Index by Industry: All Other Basic Organic Chemical Manufacturing: Primary Products'],
    ['CPALTT01DEM659N', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for Germany'],
    ['CPALTT01DEM657N', 'Consumer Price Index: All Items: Total for Germany'],
    ['DEUCPALTT01IXOBSAM', 'Consumer Price Indices (CPIs, HICPs), COICOP 1999: Consumer Price Index: Total for Germany'],
    ['DEUCPALTT01IXNBM', 'Consumer Price Index: All Items: Total for Germany'],
    ['TXUR', 'Unemployment Rate in Texas'],
    ['CUSR0000SETG01', 'Consumer Price Index for All Urban Consumers: Airline Fares in U.S. City Average'],
    ['BAMLC4A0C710YEY', 'ICE BofA 7-10 Year US Corporate Index Effective Yield'],
    ['USSERV', 'All Employees, Other Services'],
    ['PCU311421311421', 'Producer Price Index by Industry: Fruit and Vegetable Canning'],
    ['RBUSBIS', 'Real Broad Effective Exchange Rate for United States'],
    ['PPIDFS', 'Producer Price Index by Commodity: Final Demand: Final Demand Foods'],
    ['WPU0638', 'Producer Price Index by Commodity: Chemicals and Allied Products: Pharmaceutical Preparations'],
    ['M12MTVUSM227NFWA', 'Moving 12-Month Total Vehicle Miles Traveled'],
    ['WPU0561', 'Producer Price Index by Commodity: Fuels and Related Products and Power: Crude Petroleum (Domestic Production)'],
    ['NASDAQ100', 'NASDAQ 100 Index'],
    ['WPU083', 'Producer Price Index by Commodity: Lumber and Wood Products: Plywood'],
    ['PCU332510332510', 'Producer Price Index by Industry: Hardware Manufacturing'],
    ['WPU571', 'Producer Price Index by Commodity: Wholesale Trade Services: Machinery and Equipment and Parts and Supplies Wholesaling'],
    ['PCOALAUUSDM', 'Global price of Coal, Australia'],
    ['PCOALAUUSDA', 'Global price of Coal, Australia'],
    ['PPITSS', 'Producer Price Index by Commodity: Final Demand: Final Demand Trade Services'],
    ['PCU532412532412', 'Producer Price Index by Industry: Other Heavy Machinery Rental and Leasing'],
    ['PCU332618332618', 'Producer Price Index by Industry: Other Fabricated Wire Product Manufacturing'],
    ['NYXRSA', 'S&P CoreLogic Case-Shiller NY-New York Home Price Index'],
    ['MKTGNIUSA646NWDB', 'Gross National Income for United States'],
    ['PCU332322332322', 'Producer Price Index by Industry: Sheet Metal Work Manufacturing'],
    ['PCU481111481111', 'Producer Price Index by Industry: Scheduled Passenger Air Transportation'],
    ['WPU4511', 'Producer Price Index by Commodity: Professional Services (Partial): Legal Services'],
    ['RIFLPBCIANM60NM', 'Finance Rate on Consumer Installment Loans at Commercial Banks, New Autos 60 Month Loan'],
    ['DAXRNSA', 'S&P CoreLogic Case-Shiller TX-Dallas Home Price Index'],
    ['IMPGS', 'Imports of Goods and Services'],
    ['WPUID62', 'Producer Price Index by Commodity: Intermediate Demand by Commodity Type: Unprocessed Goods for Intermediate Demand'],
    ['PCU33441K33441K', 'Producer Price Index by Industry: Capacitor, Resistor, Coil, Transformer, and Other Inductor Manufacturing'],
    ['PCU335931335931', 'Producer Price Index by Industry: Current-Carrying Wiring Device Manufacturing'],
    ['CHXRSA', 'S&P CoreLogic Case-Shiller IL-Chicago Home Price Index'],
    ['WPU029', 'Producer Price Index by Commodity: Processed Foods and Feeds: Prepared Animal Feeds'],
    ['APU0000701111', 'Average Price: Flour, White, All Purpose (Cost per Pound/453.6 Grams) in U.S. City Average'],
    ['WPU5111', 'Producer Price Index by Commodity: Health Care Services: Outpatient Care (Partial)'],
    ['PCEDGC96', 'Real Personal Consumption Expenditures: Durable Goods'],
    ['PCU621111621111', 'Producer Price Index by Industry: Offices of Physicians, Except Mental Health'],
    ['MEHOINUSCAA646N', 'Median Household Income in California'],
    ['PPITWS', 'Producer Price Index by Commodity: Final Demand: Final Demand Services Less Trade, Transportation, and Warehousing'],
    ['PPITTW', 'Producer Price Index by Commodity: Final Demand: Final Demand Services Less Trade, Transportation, and Warehousing'],
    ['PPIAWS', 'Producer Price Index by Commodity: Final Demand: Final Demand Transportation and Warehousing Services'],
    ['WPUID63', 'Producer Price Index by Commodity: Intermediate Demand by Commodity Type: Services for Intermediate Demand'],
    ['MEFAINUSA646N', 'Median Family Income in the United States'],
    ['DRSREACBS', 'Delinquency Rate on Loans Secured by Real Estate, All Commercial Banks'],
    ['WDDNS', 'Demand Deposits'],
    ['TCMDO', 'All Sectors; Debt Securities and Loans; Liability, Level'],
    ['AMBSL', 'St. Louis Adjusted Monetary Base (DISCONTINUED)'],
    ['TLRESCONS', 'Total Construction Spending: Residential in the United States'],
    ['ACTLISCOU38060', 'Housing Inventory: Active Listing Count in Phoenix-Mesa-Scottsdale, AZ (CBSA)'],
    ['CP0000EZ19M086NEST', 'Harmonized Index of Consumer Prices: All Items for Euro area (19 countries)'],
    ['PRAWMINDEXM', 'Global price of Agr. Raw Material Index'],
    ['WPUID51', 'Producer Price Index by Commodity: Intermediate Demand by Production Flow: Stage 1 Intermediate Demand'],
    ['GASDESW', 'US Diesel Sales Price'],
    ['PSUNOUSDM', 'Global price of Sunflower Oil'],
    ['WPUID53', 'Producer Price Index by Commodity: Intermediate Demand by Production Flow: Stage 3 Intermediate Demand'],
    ['WFRBLB50107', 'Total Net Worth Held by the Bottom 50% (1st to 50th Wealth Percentiles)'],
    ['WPUID54', 'Producer Price Index by Commodity: Intermediate Demand by Production Flow: Stage 4 Intermediate Demand'],
    ['WPU3911', 'Producer Price Index by Commodity: Credit Intermediation Services (Partial): Business Loans (Partial)'],
    ['LNS14000024', 'Unemployment Rate - 20 Yrs. & over'],
    ['PCEND', 'Personal Consumption Expenditures: Nondurable Goods'],
    ['NA000348Q', 'Personal Consumption Expenditures: Nondurable Goods'],
    ['DTWEXAFEGS', 'Nominal Advanced Foreign Economies U.S. Dollar Index'],
    ['CRESTKCPIXSLTRM159SFRBATL', 'Sticky Price Consumer Price Index less Food, Energy, and Shelter'],
    ['M1', 'M1 (DISCONTINUED)'],
    ['WPUID52', 'Producer Price Index by Commodity: Intermediate Demand by Production Flow: Stage 2 Intermediate Demand'],
    ['CLVMNACSCAB1GQFR', 'Real Gross Domestic Product for France'],
    ['EXCSRESNS', 'Excess Reserves of Depository Institutions (DISCONTINUED)'],
    ['DGDSRX1', 'Real Personal Consumption Expenditures: Goods'],
    ['LNS14000031', 'Unemployment Rate - 20 Yrs. & over, Black or African American Men'],
    ['APU0000FS1101', 'Average Price: Butter, Stick (Cost per Pound/453.6 Grams) in U.S. City Average'],
    ['STTMINWGMI', 'State Minimum Wage Rate for Michigan'],
    ['SOFR180DAYAVG', '180-Day Average SOFR'],
    ['PHXRNSA', 'S&P CoreLogic Case-Shiller AZ-Phoenix Home Price Index'],
    ['ATNHPIUS38060Q', 'All-Transactions House Price Index for Phoenix-Mesa-Chandler, AZ (MSA)'],
    ['W398RC1A027NBEA', 'Household saving'],
    ['POPTOTUSA647NWDB', 'Population, Total for United States'],
    ['IR3TIB01USM156N', 'Interest Rates: 3-Month or 90-Day Rates and Yields: Interbank Rates: Total for United States'],
    ['ECOMSA', 'E-Commerce Retail Sales'],
    ['PBARLUSDM', 'Global price of Barley'],
    ['WSHOSHO', 'Assets: Securities Held Outright: Securities Held Outright: Wednesday Level'],
    ['LES1252881500Q', 'Employed full time: Median usual weekly nominal earnings (second quartile): Wage and salary workers: 16 years and over'],
    ['RTWEXBGS', 'Real Broad Dollar Index'],
    ['A053RC1Q027SBEA', 'National income: Corporate profits before tax (without IVA and CCAdj)'],
    ['MIXRNSA', 'S&P CoreLogic Case-Shiller FL-Miami Home Price Index'],
    ['EXPGS', 'Exports of Goods and Services'],
    ['REALLN', 'Real Estate Loans, All Commercial Banks'],
    ['QHKR628BIS', 'Real Residential Property Prices for Hong Kong SAR'],
    ['Q09084USQ507NNBR', 'Mortgage Delinquency Rates for United States'],
    ['GCEC1', 'Real Government Consumption Expenditures and Gross Investment'],
    ['LNS12500000', 'Employed, Usually Work Full Time'],
    ['IEABC', 'Balance on current account'],
    ['PMAIZMTUSDM', 'Global price of Corn'],
    ['TNWBSHNO', 'Households and Nonprofit Organizations; Net Worth, Level'],
    ['WORAL', 'Assets: Other: Repurchase Agreements: Wednesday Level'],
    ['DEXINUS', 'Indian Rupees to U.S. Dollar Spot Exchange Rate'],
    ['LNU00074597', 'Population - With a Disability, 16 Years and over'],
    ['TSIFRGHT', 'Freight Transportation Services Index'],
    ['ACOGNO', "Manufacturers' New Orders: Consumer Goods"],
    ['UCOGNO', "Manufacturers' New Orders: Consumer Goods"],
    ['PPOILUSDM', 'Global price of Palm Oil'],
    ['EXSFHSUSM495S', 'Existing Single-Family Home Sales'],
    ['ECIALLCIV', 'Employment Cost Index: Total compensation: All Civilian'],
    ['MEDLISPRIPERSQUFEEUS', 'Housing Inventory: Median Listing Price per Square Feet in the United States'],
    ['NJSTHPI', 'All-Transactions House Price Index for New Jersey'],
    ['CASACBW027SBOG', 'Cash Assets, All Commercial Banks'],
    ['WJFUELUSGULF', 'Kerosene-Type Jet Fuel Prices: U.S. Gulf Coast'],
    ['CARACBW027SBOG', 'Consumer Loans: Other Consumer Loans: Automobile Loans, All Commercial Banks'],
    ['BOXRSA', 'S&P CoreLogic Case-Shiller MA-Boston Home Price Index'],
    ['CUUR0000SA0L2', 'Consumer Price Index for All Urban Consumers: All Items Less Shelter in U.S. City Average'],
    ['DFII20', 'Market Yield on U.S. Treasury Securities at 20-Year Constant Maturity, Quoted on an Investment Basis, Inflation-Indexed'],
    ['DNXRSA', 'S&P CoreLogic Case-Shiller CO-Denver Home Price Index'],
    ['BOGZ1FL073161113Q', 'Interest Rates and Price Indexes; 10-Year Treasury Yield, Level'],
    ['PCESC96', 'Real Personal Consumption Expenditures: Services'],
    ['ACDGNO', "Manufacturers' New Orders: Consumer Durable Goods"],
    ['MMTY', 'Treasury Yield: Money Market <100M'],
    ['WLCFLL', 'Assets: Liquidity and Credit Facilities: Loans: Wednesday Level'],
    ['VXVCLS', 'CBOE S&P 500 3-Month Volatility Index'],
    ['BAMLCC0A0CMTRIV', 'ICE BofA US Corporate Index Total Return Index Value'],
    ['DRTSCIS', 'Net Percentage of Domestic Banks Tightening Standards for Commercial and Industrial Loans to Small Firms'],
    ['CES9091000001', 'All Employees, Federal'],
    ['A072RC1Q156SBEA', 'Personal saving as a percentage of disposable personal income'],
    ['WPUFD49207', 'Producer Price Index by Commodity: Final Demand: Finished Goods'],
    ['ADXTNO', "Manufacturers' New Orders: Durable Goods Excluding Transportation"],
    ['GVZCLS', 'CBOE Gold ETF Volatility Index'],
    ['NFCILEVERAGE', 'Chicago Fed National Financial Conditions Leverage Subindex'],
    ['PCOTTINDUSDM', 'Global price of Cotton'],
    ['CES0500000011', 'Average Weekly Earnings of All Employees, Total Private'],
    ['LNS11324230', 'Labor Force Participation Rate - 55 Yrs. & over'],
    ['WPU1012', 'Producer Price Index by Commodity: Metals and Metal Products: Iron and Steel Scrap'],
    ['GEPUCURRENT', 'Global Economic Policy Uncertainty Index: Current Price Adjusted GDP'],
    ['CSCICP03USM665S', 'Composite Leading Indicators: Composite Consumer Confidence Amplitude Adjusted for United States'],
    ['A34SNO', "Manufacturers' New Orders: Computers and Electronic Products"],
    ['STTMINWGCA', 'State Minimum Wage Rate for California'],
    ['W875RX1', 'Real personal income excluding current transfer receipts'],
    ['FPCPITOTLZGJPN', 'Inflation, consumer prices for Japan'],
    ['MDLM', 'Other Liquid Deposits: Total'],
    ['CFNAI', 'Chicago Fed National Activity Index'],
    ['PNFIC1', 'Real Private Nonresidential Fixed Investment'],
    ['PB0000091Q225SBEA', 'Real Average of GDP and GDI'],
    ['OVXCLS', 'CBOE Crude Oil ETF Volatility Index'],
    ['BOGZ1FL403069330Q', 'Government-Sponsored Enterprises; FHLB Advances; Asset, Level'],
    ['MASTHPI', 'All-Transactions House Price Index for Massachusetts'],
]

if __name__ == "__main__":
    from .www import fetch_html
    def get_fred_series():
        from bs4 import BeautifulSoup

        def extract_links_from_h3(html):
            """
            Extracts all links (URL and text) that are inside <h3> tags from the provided HTML text.
            """
            if html is None:
                raise ValueError("Provided HTML is None.")
            
            soup = BeautifulSoup(html, "html.parser")
            links = []

            for h3 in soup.find_all("h3"):
                for a_tag in h3.find_all("a", href=True):
                    url = a_tag["href"]
                    text = a_tag.get_text(strip=True)
                    links.append((url, text))
            
            return links


        orig_url = "https://fred.stlouisfed.org/tags/series?t=&et=&ob=pv&od=&tg=&tt=&pageID="

        results = []
        for i in range(30):
            
            full_url = orig_url+str(i+1)
            print(full_url)
            html = fetch_html(full_url)

            extracted_links = extract_links_from_h3(html)
            for url, text in extracted_links:
                if url.startswith("/series/"):
                    id = url.split('/')[2]
                    if id in results:
                        continue
                    
                    results.append([id, text.strip()])
            